backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'optiken'
    label: 'Optiken'
    folder: 'src/pages/optiken'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'optiken-post',
        }
      - { label: 'Titel', name: 'title', widget: 'string' }
      - {
          label: 'Schlagwortbeschreibung',
          name: 'description',
          widget: 'string',
          hint: 'kurze Schlagwortbeschreibung',
        }
      - {
          label: Optik Bild,
          name: image,
          widget: image,
          hint: '.png Images funktionieren am Besten',
        }
      - { label: 'Text', name: 'body', widget: 'markdown' }
      - { label: 'Technische Daten', name: 'vehicleData', widget: 'markdown' }
      - {
          label: 'Featured',
          name: 'featured',
          widget: 'string',
          hint: 'Ja oder Nein',
        }

      - {
          label: 'Kategorie',
          name: 'category',
          widget: 'select',
          options:
            [
              'Dienstgläser',
              'Entfernungsmesser',
              'Panzer Optiken',
              'Waffen Optiken',
              'Geschütz Optiken',
              'Beobachtungs Optiken',
              'Neuheiten',
              'Sonstiges',
            ],
        }

  - name: 'blog'
    label: 'News'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Titel', name: 'title', widget: 'string' }
      - {
          label: Bild,
          name: blogimage,
          widget: image,
          hint: '.png Images funktionieren am Besten',
        }
      - {
          label: 'Schlagwortbeschreibung',
          name: 'description',
          widget: 'string',
          hint: 'kurze Schlagwortbeschreibung',
        }
      - { label: 'Text', name: 'body', widget: 'markdown' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          hint: 'z.B.: #Flohmarkt, #Optiken, #1.Weltkrieg, #Ausstellung',
        }
      - { label: 'Datum', name: 'date', widget: 'datetime' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/home/index.md'
        label: 'Landing Page'
        name: 'home'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'home-page',
            }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Subtitel, name: subtitle, widget: text },
                ],
            }

      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/impressum/index.md'
        label: 'Impressum'
        name: 'impressum'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'impressum-page',
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/datenschutz.md'
        label: 'Datenschutz'
        name: 'datenschutz'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'datenschutz-page',
            }
          - { label: 'Titel', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/footer/index.md'
        label: 'Footer'
        name: 'footer'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'footer',
            }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Bild, name: logo, widget: image },
                  { label: Title, name: title, widget: string },
                  { label: Subtitel, name: subtitle, widget: text },
                ],
            }
